os: osx
osx_image: xcode10.2
language: objective-c
sudo: false
env:
  global:
  - THEOS=~/theos
before_install:
  - brew update
  - brew install dpkg ldid
  - git clone --recursive git://github.com/theos/theos.git ~/theos
script:
  - "export VERSION=$(grep 'Version: ' control | sed 's/^.*: //')"
  - "export DESCRIPTION=$(awk '/## v$VERSION/{getline; print}' README.md)"
  - "export FILENAME='packages/'\"$(grep 'Package: ' control | sed 's/^.*: //')\"'_'\"$VERSION\"'_iphoneos-arm.deb'"
  - make package
before_deploy:
  - git config --local user.name "Jeff Rescignano"
  - git config --local user.email "jeff@jeffresc.com"
  - git tag -a v$VERSION -m "$DESCRIPTION"
deploy:
  provider: releases
  api_key:
    secure: NLTdFKYStTkAZ1LWGZlLVXzSHQbW8hGO0dfnx4UoET4KQTmdyg5nXkUei+3Nehkxe6AzBdeS1vYdmTQ2CeIQuDz5IbCYp4LOi1Y+PVnTY/njizPlSRUzukm84bCkkCWtWudsr1fxWFK0+IrG1iFIKPBw88Mus3mII1Rg86DAZtGhE4zziIqAh3dj2+gxaztpvqpl6hUcAIaVSrZqdRLSCfQico0Vk57etqEtZlSSWnB0iko3BbYBx27PflCWn9BIGNFfAbQEz3j6vnZk0kpc9n705m1ipo0NFVLOdyM3AwgwnsbveYYAjXZvS+C2Bh0GHYj6ekcWTrRS1UYoz+2w1jHAFL/on8o6ZoG85sFapCxVk+96qU2ZFX46gDbwbI3/nXcXif++yWl/JBKKx0Vo0PtWyEexZ2wvySzHxvv6KFEm3CneULDRNuU9ITpb6FRatRDiwYBsIPh1/5BoQ9UTyq0079AXgYlheR33g1gU2Sp997XVZNPsoBysgHDrsFTW2rH5Y4SuvKwZYTs06IxPjsS1+X+LX0bJ3FZHq4VlNqgVFj4G1AiqD3wAeDHK/mAx70/LRYktiSCwAPrxKGy9fhwbutCE2Zj79gIqc8Iv61YQNTX9dDOdezp2nHltJoR7+8QxxTtOaK3N9luMWJVKEoh9pLieS/OGNcg2sdIYWl8=
  file: $FILENAME
  skip_cleanup: true
  on:
    branches:
      only:
        - master
branches:
  except:
  - /^untagged/
